// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0w6fJJa8olLCjnwettPWhQtSzOHbhfTE',
    appId: '1:383802790584:web:878b5a029eb2857ace9a4d',
    messagingSenderId: '383802790584',
    projectId: 'ecommerce-56960',
    authDomain: 'ecommerce-56960.firebaseapp.com',
    storageBucket: 'ecommerce-56960.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDClVYEGkNwHx3SUOjWpYY3ACJNgjshgI0',
    appId: '1:383802790584:android:fecda36cdd3002a6ce9a4d',
    messagingSenderId: '383802790584',
    projectId: 'ecommerce-56960',
    storageBucket: 'ecommerce-56960.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXfCBaLDGpztE8cpFPydynKwlKH3T-hOk',
    appId: '1:383802790584:ios:4a594972d41e8c58ce9a4d',
    messagingSenderId: '383802790584',
    projectId: 'ecommerce-56960',
    storageBucket: 'ecommerce-56960.appspot.com',
    iosBundleId: 'com.NiMs.ecommerc.ecommerc',
  );
}
